questions = [
{ "text": "Sharks are mammals.", "isTrue": False },
{ "text": "Sea otters have a favorite rock they use to break open food.", "isTrue": True },
{ "text": "The blue whale is the biggest animal to have ever lived.", "isTrue": True },
{ "text": "The hummingbird egg is the world's smallest bird egg.", "isTrue": True },
{ "text": "Pigs roll in the mud because they don't like being clean.", "isTrue": False },
{ "text": "Bats are blind.", "isTrue": False },
{ "text": "A dog sweats by panting its tongue.", "isTrue": False },
{ "text": "It takes a sloth two weeks to digest a meal.", "isTrue": True },
{ "text": "The largest living frog is the Goliath frog of West Africa.", "isTrue": True },
{ "text": "An ant can lift 1,000 times its body weight.", "isTrue": False },
{ "text": "When exiting a cave, bats always go in the direction of the wind.", "isTrue": False },
{ "text": "Galapagos tortoises sleep up to 16 hours a day.", "isTrue": True },
{ "text": "An octopus has seven hearts.", "isTrue": False },
{ "text": "The goat is the national animal of Scotland.", "isTrue": False },
{ "text": "Herbivores are animal eaters.", "isTrue": False },
{ "text": "A monkey was the first non-human to go into space.", "isTrue": False },
{ "text": "New York City is composed of between 36 and 42 islands.", "isTrue": True },
{ "text": "South Africa has one capital.", "isTrue": False },
{ "text": "The Atlantic Ocean is the biggest ocean on Earth.", "isTrue": False },
{ "text": "Mount Everest is the tallest mountain in the world.", "isTrue": True },
{ "text": "You can find the 'Desert of Death' in California.", "isTrue": False },
{ "text": "The total length of the Great Wall of China adds up to 13,171 miles.", "isTrue": True },
{ "text": "The two longest rivers in the world are the Mississippi and the Nile.", "isTrue": False },
{ "text": "The Chunnel between England and France is 31.5 miles long.", "isTrue": True },
{ "text": "Greenland is the largest island in the world.", "isTrue": True },
{ "text": "There are more countries in South America than Africa.", "isTrue": False },
{ "text": "Alaska has the most active volcanoes of any state in the United States.", "isTrue": True },
{ "text": "China has the longest coastline in the world.", "isTrue": False },
{ "text": "Vatican City is the smallest country in the world.", "isTrue": True },
{ "text": "Venezuela is home to the world's highest waterfall.", "isTrue": True },
{ "text": "The human body has four lungs.", "isTrue": False },
{ "text": "Human skin regenerates every week.", "isTrue": False },
{ "text": "The average human sneeze can be clocked at 100 miles an hour.", "isTrue": True },
{ "text": "Humans lose an average of 75 strands of hair a month.", "isTrue": False },
{ "text": "Infants have more bones than adults.", "isTrue": True },
{ "text": "The heart is the largest internal organ in the body.", "isTrue": False },
{ "text": "Most of the human brain is made of muscle.", "isTrue": False },
{ "text": "Taste buds can only be found on the tongue.", "isTrue": False },
{ "text": "The human eye can distinguish 10 million different colors.", "isTrue": True },
{ "text": "Humans lose more than 80% of heat from their feet.", "isTrue": False },
{ "text": "The human body is about 60% water.", "isTrue": True },
{ "text": "The most common blood type is 0- negative.", "isTrue": True },
{ "text": "Aladdin's character was based on Brad Pitt.", "isTrue": False },
{ "text": "The song “We Don't Talk About Bruno” from Encanto is the first Disney song to hit #1 on the Billboard Hot 100 chart in 29 years.", "isTrue": True },
{ "text": "It took eight months from start to finish to produce the 1959 Disney film, Sleeping Beauty.", "isTrue": False },
{ "text": "Pinocchio was the first animated, full-color Walt Disney feature film.", "isTrue": False },
{ "text": "Toy Story was Pixar's first movie.", "isTrue": True },
{ "text": "Minnie Mouse's full name is Wilhelmina Mouse.", "isTrue": False },
{ "text": "Dumbo is the shortest Disney film.", "isTrue": True },
{ "text": "The Aristocats was the first film to be made after Walt Disney's death.", "isTrue": True },
{ "text": "Prince Eric and Ariel from The Little Mermaid have a daughter named Princess Song.", "isTrue": False },
{ "text": "Beauty and the Beast was Disney's first Broadway musical.", "isTrue": True },
{ "text": "Pepperoni is the most popular pizza topping in the US.", "isTrue": True },
{ "text": "Cheesecake comes from Italy.", "isTrue": False },
{ "text": "Pineapples grow on trees.", "isTrue": False },
{ "text": "A potato was the first vegetable to be planted on the space shuttle.", "isTrue": True },
{ "text": "Hawaiian pizza comes from Canada.", "isTrue": True },
{ "text": "French fries originated from France.", "isTrue": False },
{ "text": "Pizza was the first food consumed in space.", "isTrue": False },
{ "text": "Caesar Salad originates from Italy.", "isTrue": False },
{ "text": "Ears of corn have an even number of rows.", "isTrue": True },
{ "text": "The names of the mascots for Rice Krispies are Snap, Crackle, & Pop.", "isTrue": True },
{ "text": "Vanilla is the world's most expensive spice.", "isTrue": False },
{ "text": "Mcdonald's has the most restaurants by location in the United States.", "isTrue": False },
{ "text": "The Chinese New Year is celebrated on the same day every year.", "isTrue": False },
{ "text": "Punxsutawney Phil is just a nickname for the famous groundhog.", "isTrue": True },
{ "text": "The first St. Patrick's Day parade in the United States was held in New York City.", "isTrue": False },
{ "text": "The tradition of dyeing Easter eggs started in the United States.", "isTrue": False },
{ "text": "Only two men signed the Declaration of Independence on July 4, 1776.", "isTrue": True },
{ "text": "The U.S. and Canada celebrate Thanksgiving on the same day.", "isTrue": False },
{ "text": "Santa Claus has his own postal code.", "isTrue": True },
{ "text": "There are seven nights in Kwanzaa.", "isTrue": True },
{ "text": "Memorial Day has a special set of instructions regarding raising and lowering the U.S. flag.", "isTrue": True },
{ "text": "Polo takes up the largest amount of space in terms of land area.", "isTrue": True },
{ "text": "Every golf ball has the same number of dimples.", "isTrue": False },
{ "text": "Football players started wearing helmets in 1943.", "isTrue": True },
{ "text": "Brazil is the only nation to have played in every World Cup finals tournament.", "isTrue": True },
{ "text": "World-renowned jeweler Tiffany & Co. is the maker of the Vince Lombardi trophy.", "isTrue": True },
{ "text": "There are 30 NFL teams.", "isTrue": False },
{ "text": "The New York Marathon is the largest in the world.", "isTrue": True },
{ "text": "Three strikes in a row in bowling is called a chicken.", "isTrue": False },
{ "text": "An astronaut has played golf on the moon.", "isTrue": True },
{ "text": "The Tour de France always finishes in Italy.", "isTrue": False },
{ "text": "Soccer (football) is estimated to have more than 2 billion fans around the world.", "isTrue": False },
{ "text": "President George Washington brought macaroni and cheese to the USA.", "isTrue": False },
{ "text": "Marvel published its first comic in October 1939.", "isTrue": True },
{ "text": "The letter “T” is the most common in the English Language.", "isTrue": False },
{ "text": "People who have chiclephobia are afraid of cats.", "isTrue": False },
{ "text": "John Glenn became the oldest astronaut when he traveled to space at the age of 53.", "isTrue": False },
{ "text": "All the kings in a standard deck of cards have a mustache.", "isTrue": False },
{ "text": "Pepsi was the first soft drink to be enjoyed in outer space.", "isTrue": False },
{ "text": "The name of Batman's butler is Albert.", "isTrue": False },
{ "text": "Fortune cookies were invented in China.", "isTrue": False },
{ "text": "Henry VIII had eight wives.", "isTrue": False },
{ "text": "The maximum length for a video posted on TikTok is 45 seconds.", "isTrue": False },
{ "text": "The letter “J” is the only letter in the alphabet not included in the periodic table.", "isTrue": True },
{ "text": "Every country in the world has a rectangular flag.", "isTrue": False },
{ "text": "The Harry Potter film, Chamber of Secrets, is the longest film of the Harry Potter movies.", "isTrue": True },
{ "text": "The official color of the Golden Gate Bridge in California is “Tennessee Orange.”", "isTrue": False },
{ "text": "Dr. Pepper is the oldest soft drink in America.", "isTrue": True },
]